[server]
headless = true
enableCORS = false
enableXsrfProtection = false

[theme]
primaryColor = "#00D4FF"
backgroundColor = "#0E1417"
secondaryBackgroundColor = "#1A2123"
textColor = "#DDE3E7"
font = "sans serif"
